# generated by datamodel-codegen:
#   filename:  resume-schema.json
#   timestamp: 2024-11-10T06:30:47+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Model(BaseModel):
    __root__: Any = Field(..., description='A JSON schema for a resume')
